<%@ Page Title="" Language="C#" MasterPageFile="~/Masterpage.master" AutoEventWireup="true" CodeFile="viewcart.aspx.cs" Inherits="viewcart" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" Runat="Server">
    <table align="center" border="1">
        <tr>
            <td align="center" class="style8" colspan="2">
                <center>
                    <b>CUSTOMER ORDER</b>
                </center>
                Order Date-<asp:Label ID="Label5" runat="server" 
                    Text="Label"></asp:Label>
            </td>
        </tr>
        <tr>
            <td class="style8">
                Customer Id</td>
            <td class="style7">
                <asp:Label ID="Label1" runat="server" 
                    Text="Label"></asp:Label>
            </td>
        </tr>
        <tr>
            <td class="style8">
                Customer Name</td>
            <td class="style7">
                <asp:Label ID="Label2" runat="server" 
                    Text="Label"></asp:Label>
            </td>
        </tr>
        <tr>
            <td class="style8">
                Address</td>
            <td class="style7">
                <asp:Label ID="Label3" runat="server" 
                    Text="Label"></asp:Label>
            </td>
        </tr>
        <tr>
            <td class="style8">
                Contact</td>
            <td class="style7">
                <asp:Label ID="Label4" runat="server" 
                    Text="Label"></asp:Label>
            </td>
        </tr>
        <tr>
            <td class="style8" colspan="2">
                <asp:GridView ID="GridView1" runat="server" 
                    AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" 
                    AutoGenerateSelectButton="True" 
                    BackColor="#FFCC66" BorderColor="Blue" 
                    BorderStyle="None" BorderWidth="1px" 
                    CellPadding="4" HorizontalAlign="Left" 
                    onrowdeleting="GridView1_RowDeleting" 
                    ShowFooter="True" Width="279px">
                    <FooterStyle BackColor="#FFFFCC" 
                        ForeColor="#330099" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" 
                        ForeColor="#FFFFCC" />
                    <PagerStyle BackColor="#FFFFCC" 
                        ForeColor="#330099" HorizontalAlign="Center" />
                    <RowStyle BackColor="White" ForeColor="#330099" />
                    <SelectedRowStyle BackColor="#FFCC66" 
                        Font-Bold="True" ForeColor="#663399" />
                    <SortedAscendingCellStyle BackColor="#FEFCEB" />
                    <SortedAscendingHeaderStyle BackColor="#AF0101" />
                    <SortedDescendingCellStyle BackColor="#F6F0C0" />
                    <SortedDescendingHeaderStyle BackColor="#7E0000" />
                    <Columns>
                        <asp:BoundField DataField="Pid" 
                            HeaderText=" Product_Id" />
                        <asp:BoundField DataField="Pname" 
                            HeaderText=" Name" />
                        <asp:BoundField DataField="Quantity" 
                            HeaderText=" Quantity" />
                        <asp:BoundField DataField="Price" 
                            HeaderText=" Price" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
    <center>
        <asp:Label ID="Label6" runat="server" 
            BackColor="#3399FF" BorderColor="#FF0066" 
            ForeColor="#CC0000" 
            Text="Payment Mode: CASH ON DELIVERY" 
            Width="400px"></asp:Label>
        <br />
        <br />
        <asp:Button ID="Button1" runat="server" 
            onclick="Button1_Click1" Text="Place Order" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button2" runat="server" 
            onclick="Button2_Click1" 
            Text="Cancel Your Order" />
        ,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="Button3" runat="server" 
            onclick="Button3_Click" Text="Print Bill" />
    </center>
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="ContentPlaceHolder4" Runat="Server">
</asp:Content>

